Update images
yalla-coop/website-redesign pull request #94
Opened 2020-11-02 10:32 UTC by thejoefriel

**Issue**: #refrence the relates issues here

## What did I do?
Please provide a fine description of the changes you have,
it's recommended to use lists and checklists
to include the things you have done and things left to be done for example:

- [ ] Change th title of the document
- [ ] Style the main button

## How to test?
If possible provide us with a way to test your code maybe like checking storybook or run some tests that you have made

2020-11-02 11:23 UTC, jema28 requested changes

2020-11-02 11:23 UTC, jema28 commented on src/pages/presspad.js
> +            fileName="presspad-figma"
Looks good @thejoefriel, I think we need to change the alt text here too though

2020-11-02 11:23 UTC, jema28 commented
@thejoefriel Can you change the base of this branch to release-v1?

2020-11-02 19:08 UTC, yosefanajjar commented
@jema28 done

2020-11-03 05:26 UTC, jema28 commented
Been thinking about this and I think the landing page is cleaner without the photo under who we are @thejoefriel. It doesn't quite fit in the colour scheme currently but happy with the rest of the changes

2020-11-03 05:48 UTC, jema28 commented
Agreed on the image files sizes @yosefanajjar and loading times, just want to make sure they don't become pixelated/too small.

2020-11-03 08:40 UTC, thejoefriel commented
Ok have made the changes @jema28 if you want to review and merge in.

I've left the team image in there though. At the moment there's nothing that shows us on the landing page. I think this is really important, especially since I personally feel the header image looks like a stock image. I appreciate there are different colours so I'm happy for you to edit, but we need to show people and who we are on this website otherwise it doesn't look trustworthy

2020-11-03 08:45 UTC, jema28 commented
Hey @thejoefriel, yeh I agree, what about if we use this image as the header instead? I initially used it for the story and team but I think it would work work really nicely on the landing page. What do you think? 

<img width="881" alt="Screenshot 2020-11-03 at 08 42 27" src="https://user-images.githubusercontent.com/25960351/97964535-d4688000-1db0-11eb-8920-9608c44d23fe.png">

2020-11-03 09:15 UTC, merged